const { emitEnvelope } = require("../communication/envelope");
const sessionStore = require("../session/sessionStore");
const sessionRepository = require("../session/sessionRepository");
const logger = require("../logs/logger");

// 03-LIVE-INTERVIEW-MODULE.md §8: presents the case and hard-stops — sets
// the awaitingCaseAcknowledgement gate so no case question can be asked
// until acknowledgeCase() below is explicitly triggered by the candidate.
// `brief` is the AI's spoken narration (already generated by
// interviewController.js via questionGenerator.generateCasePresentation);
// `content` is the raw case text the doc's contract expects in this payload.
async function presentCase(io, sessionId, caseContentText, brief) {
  await sessionStore.touchSession(sessionId, { awaitingCaseAcknowledgement: true });
  await emitEnvelope(io, sessionId, "case.presented", { content: caseContentText || null, brief: brief || null });
}

// 03-LIVE-INTERVIEW-MODULE.md §8: "the only point in the flow explicitly
// gated on a manual UI action." Lazy-requires interviewController to avoid a
// circular require (interviewController -> caseFlowController -> interviewController),
// same technique already used by interviewController.js's endSession/peerConnectionManager.
async function acknowledgeCase(io, sessionId) {
  const session = await sessionStore.getSession(sessionId);
  if (!session || !session.awaitingCaseAcknowledgement) {
    logger.warn(`case.acknowledged received with nothing awaiting acknowledgement sessionId=${sessionId}`);
    return;
  }

  await sessionStore.touchSession(sessionId, { awaitingCaseAcknowledgement: false });
  sessionRepository.markCaseAcknowledged(sessionId); // fire-and-forget
  await emitEnvelope(io, sessionId, "case.acknowledged", {});

  const interviewController = require("../interviewer/interviewController");
  await interviewController.askNextQuestion(io, sessionId, "CASE");
}

module.exports = { presentCase, acknowledgeCase };
